environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Engine
      PROJECT_DETAILS: "Game Creator"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Game
      PROJECT_DETAILS: "Game Runner"

install:
  - cd %PROJECT%
  - 7z a %PROJECT%.zip %APPVEYOR_BUILD_FOLDER%/%PROJECT%/%PROJECT%.pro

build: off

artifacts:
  - path: $(PROJECT)/$(PROJECT).zip
    name: $(PROJECT)

deploy:
  release: "$(PROJECT) $(appveyor_build_version)"
  description: $(PROJECT_DETAILS)
  provider: GitHub
  auth_token: $(RELEASES_API_KEY)
  artifact: $(PROJECT)
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
