environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Engine
      PROJECT_DETAILS: "Game Creator"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Game
      PROJECT_DETAILS: "Game Runner"

install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

before_build:
  - cd %PROJECT%

build_script:
  - qmake

after_build:
  - mingw32-make
  - 7z a %PROJECT%.zip %APPVEYOR_BUILD_FOLDER%/%PROJECT%/release/%PROJECT%.exe
  - cd %APPVEYOR_BUILD_FOLDER%/%PROJECT%
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%/%PROJECT%/release
  - dir

artifacts:
  - path: $(PROJECT)/$(PROJECT).zip
    name: $(PROJECT)

deploy:
  release: "$(PROJECT) $(appveyor_build_version)"
  description: $(PROJECT_DETAILS)
  provider: GitHub
  auth_token:
    secure: w5oGPRR1c6FPZUxNya2oIAx758wmnPolSIvui2FCHNUZjOSGHP5bJ7eaUXGZ23PU
  artifact: $(PROJECT)
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
