environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Engine
      PROJECT_DETAILS: "RPG Paper Maker Engine"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT: Game
      PROJECT_DETAILS: "RPG Paper Maker Game Runner"

install:
  - cd %PROJECT%
  - 7z a %PROJECT%.zip %APPVEYOR_BUILD_FOLDER%/%PROJECT%/%PROJECT%.pro

build: off

artifacts:
  - path: $(PROJECT)/$(PROJECT).zip
    name: $(PROJECT)

deploy:
  release: "RPG Paper Maker $(PROJECT) $(appveyor_build_version)"
  description: $(PROJECT_DETAILS)
  provider: GitHub
  auth_token: $(RELEASES_API_KEY)
  artifact: $(PROJECT)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
